# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Syntax highlighting
# highlighter: rouge


# Site settings
title: Scratch for kids
email: admin@bluemasters.tk
description: > # this means to ignore newlines until "baseurl:"
  Bienvenue à notre atelier pour apprendre à programmer avec Scratch!
baseurl: /scratch-for-kids # the subpath of your site, e.g. /blog
url: http://bluemasters.github.io/ # the base hostname & protocol for your site
github_username: bluemasters
version: 1.2

# Build settings
markdown: kramdown
gems: [jekyll-gist]
exclude: [Gemfile]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
#sass:
#  sass_dir: _scss
